DROP TABLE CUSTOMERS;
DROP TABLE EMPLOYEES;
DROP TABLE PRODUCTS;
DROP TABLE SALES;


CREATE TABLE CUSTOMERS(
  CUSTOMERID int
, FIRSTNAME varchar(40)
, MIDDLEINITIAL varchar(40)
, LASTNAME varchar(40)
);

CREATE TABLE EMPLOYEES(
  EMPLOYEEID int
, FIRSTNAME varchar(40)
, MIDDLEINITIAL varchar(40)
, LASTNAME varchar(40)
);

CREATE TABLE PRODUCTS(
  PRODUCTID int
, NAME varchar(50)
, PRICE decimal(19,4)
);

CREATE TABLE SALES(
  SALESID int
, SALESPERSONID int
, CUSTOMERID int
, PRODUCTID int
, QUANTITY int
);

LOAD DATA LOCAL INFILE 'customers.txt' INTO TABLE CUSTOMERS FIELDS OPTIONALLY ENCLOSED BY '"' TERMINATED BY '~'  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'employees.txt' INTO TABLE EMPLOYEES FIELDS OPTIONALLY ENCLOSED BY '"' TERMINATED BY '~'  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'products.txt'  INTO TABLE PRODUCTS  FIELDS OPTIONALLY ENCLOSED BY '"' TERMINATED BY '~'  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'sales.txt'     INTO TABLE SALES     FIELDS OPTIONALLY ENCLOSED BY '"' TERMINATED BY '~'  LINES TERMINATED BY '\n';


