!set force true

DROP TABLE CUSTOMERS;
DROP TABLE EMPLOYEES;
DROP TABLE PRODUCTS;
DROP TABLE SALES;

CREATE TABLE CUSTOMERS(
  CUSTOMERID integer PRIMARY KEY
, FIRSTNAME varchar(40)
, MIDDLEINITIAL varchar(40)
, LASTNAME varchar(40)
);

CREATE TABLE EMPLOYEES(
  EMPLOYEEID integer PRIMARY KEY
, FIRSTNAME varchar(40)
, MIDDLEINITIAL varchar(40)
, LASTNAME varchar(40)
);

CREATE TABLE PRODUCTS(
  PRODUCTID integer PRIMARY KEY
, NAME varchar(50)
, PRICE decimal(19,4)
);

CREATE TABLE SALES(
  SALESID integer PRIMARY KEY
, SALESPERSONID integer
, CUSTOMERID integer
, PRODUCTID integer
, QUANTITY integer
);



